apiVersion: v1
kind: Service
metadata:
  labels:
    name: backend
  name: backend
  namespace: default
spec:
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    name: backend
  type: LoadBalancer
  loadBalancerIP: "34.88.224.135"