apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    owner-student: MatiasSinisalo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        owner-student: MatiasSinisalo
    spec:
      containers:
      - name: backend
        image: matiassinisalo/fullstackopen:server-latest5
        resources:
          limits:
            memory: "500M"
            cpu: "500m"
        ports:
        - containerPort: 4000
        env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: MONGODB_URI
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: SECRET
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: GOOGLE_CLIENT_SECRET
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: GOOGLE_CLIENT_ID
          - name: GOOGLE_CREATE_ACCOUNT_SECRET
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: GOOGLE_CREATE_ACCOUNT_SECRET

