apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    owner-student: MatiasSinisalo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        owner-student: MatiasSinisalo
    spec:
      containers:
      - name: backend
        resources:
          limits:
            memory: "50M"
            cpu: "50m"
        image: matiassinisalo/fullstackopen:server-dev
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: MONGODB_URI
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: SECRET
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: GOOGLE_CLIENT_SECRET
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: GOOGLE_CLIENT_ID
          - name: GOOGLE_CREATE_ACCOUNT_SECRET
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: GOOGLE_CREATE_ACCOUNT_SECRET
          - name: HY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: HY_CLIENT_SECRET
          - name: HY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: HY_CLIENT_ID
          - name: HY_CREATE_ACCOUNT_SECRET
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: HY_CREATE_ACCOUNT_SECRET

