apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
    owner-student: MatiasSinisalo
  name: frontend
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: frontend
  type: ClusterIP