apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    owner-student: MatiasSinisalo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        owner-student: MatiasSinisalo
    spec:
      containers:
      - name: frontend
        image: matiassinisalo/fullstackopen:frontend-dev
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "50M"
            cpu: "50m"
