apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-database
  labels:
    owner-student: MatiasSinisalo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-database
  template:
    metadata:
      labels:
        app: mongo-database
    spec:
      volumes:
        - name: mongo-db-storage
          persistentVolumeClaim:
            claimName: mongo-db-storage
      containers:
      - name: mongo-database
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 100Mi
        image: mongo
        ports:
          - containerPort: 27017
        volumeMounts:
            - name: mongo-db-storage
              mountPath: /data/db
        env:
          - name: MONGO_INITDB_DATABASE
            valueFrom:
              secretKeyRef:
                name: mongo-config
                key: MONGO_INITDB_DATABASE
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-config
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-config
                key: MONGO_INITDB_ROOT_PASSWORD
      