apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
  - name: backend
    image: matiassinisalo/fullstackopen:server-latest
    ports:
      - containerPort: 4000
    env:
    - name: MONGODB_URI
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: MONGODB_URI
    - name: SECRET
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: SECRET

