name: CI

on: [push]

jobs:
  buildAndTestFrontEnd:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: cd courseApplication/frontend/
      - run: npm install
      - run: npm run test -- --watchAll
