name: CI

on: [push]

jobs:
  buildAndTestFrontEnd:
     
    runs-on: ubuntu-latest
    defaults:
       run: 
        working-directory: ./courseApplication/frontend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: ls
      - run: npm install 
      - run: npm run test -- --watchAll=false
      
  buildAndTestBackEnd:
     
    runs-on: ubuntu-latest
    defaults:
       run: 
        working-directory: ./courseApplication/backend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Launch MongoDB container
        uses: supercharge/mongodb-github-action@1.9.0
        with:
         mongodb-port: 8000
         mongodb-username: localuser
         mongodb-password: localpass
      - run: npm install 
      - run: npm run test:local
